version: "3.7"
services:
  api:
    depends_on:
      - "config"
      - "discovery"
    image: image-base
    ports:
      - 9000:8080
    volumes:
      - ./jars:/jars
    environment:
      - ENCRYPTION_KEY=${ABCX}
    env_file:
      - ./image-api.env
    networks:
      - imagelib_network
  config:
    image: image-base
    ports:
      - 9001:8082
    volumes:
      - ./jars:/jars
    environment:
      - ENCRYPTION_KEY=${ABCX}
    env_file:
      - ./image-config-server.env
    networks:
      - imagelib_network
  discovery:
    depends_on:
      - "config"
    image: image-base
    ports:
      - 9002:8761
    volumes:
      - ./jars:/jars
    environment:
      - ENCRYPTION_KEY=${ABCX}
    env_file:
      - ./image-discovery.env
    networks:
      - imagelib_network
  zipkin:
    image: image-base
    ports:
      - 9003:9411
    volumes:
      - ./jars:/jars
    env_file:
      - ./image-zipkin.env
    networks:
      - imagelib_network
networks:
  imagelib_network:
    external:
      name: imagelib_network
